### ISSUE TITLE
@mockable failing on literal-type type parameters

### ISSUE THREAD

**Issue by ThijsBroersen** [zio/zio-mock#40]
I am getting the an error when generating a mock for this:

```
case class Context[T](value: String)
@accessible
trait ServiceX {
  def doSomething: RIO[Context[123], Unit]
}
```
error 
```
[E]      exception during macro expansion: 
[E]      scala.reflect.macros.ParseException: ']' expected but '(' found.
[E]             at scala.reflect.macros.contexts.Parsers.$anonfun$parse$1(Parsers.scala:35)
[E]             at scala.reflect.macros.contexts.Parsers.$anonfun$parse$1$adapted(Parsers.scala:34)
[E]             at scala.collection.mutable.LinkedHashSet.foreach(LinkedHashSet.scala:127)
[E]             at scala.reflect.macros.contexts.Parsers.parse(Parsers.scala:34)
[E]             at scala.reflect.macros.contexts.Parsers.parse$(Parsers.scala:25)
[E]             at scala.reflect.macros.contexts.Context.parse(Context.scala:18)
[E]             at scala.reflect.macros.contexts.Context.parse(Context.scala:18)
[E]             at zio.mock.MockableMacro$.impl(MockableMacro.scala:357)
```

**Comment by ThijsBroersen** [comment]
Update: any literal type parameter seems to feel:
```
@accessible
trait ServiceX {
  def doSomething: RIO[123, Unit]
}

@mockable[ServiceX]
object ServiceXMock
```

**Comment by avner-unit** [comment]
@ThijsBroersen - Hi! Have to managed to solve it? I have the same issue

**Comment by ThijsBroersen** [comment]
> @ThijsBroersen - Hi! Have to managed to solve it? I have the same issue

No, sorry.

**Comment by avner-unit** [comment]
it's a bug and I don't think the contributors here are on the issues
