### ISSUE TITLE
The macros generation fails with ZIO 2.0.11 due to dropped Scala 2.11 support

### ISSUE THREAD

**Issue by leszekgruchala** [zio/zio-mock#48]
```
java.lang.NoSuchMethodError: 'boolean zio.test.TestVersion$.isScala211()'
	at zio.mock.MockableMacro$.zio$mock$MockableMacro$$makeMock$1(MockableMacro.scala:263)
	at zio.mock.MockableMacro$$anonfun$2.applyOrElse(MockableMacro.scala:312)
	at zio.mock.MockableMacro$$anonfun$2.applyOrElse(MockableMacro.scala:310)
	at scala.collection.StrictOptimizedIterableOps.collect(StrictOptimizedIterableOps.scala:151)
	at scala.collection.StrictOptimizedIterableOps.collect$(StrictOptimizedIterableOps.scala:136)
	at scala.collection.immutable.HashMap.collect(HashMap.scala:39)
	at zio.mock.MockableMacro$.impl(MockableMacro.scala:310)
```

The ZIO 2.0.11 dropped support for Scala 2.11

**Comment by guizmaii** [comment]
Hey @leszekgruchala,

Can you maybe make a PR to drop Scala 2.11 support in zio-mock, please?

**Comment by leszekgruchala** [comment]
Yes, but not sooner then middle of next week.

**Comment by guizmaii** [comment]
See https://github.com/zio/zio-mock/pull/49

**Comment by leszekgruchala** [comment]
Thank you @guizmaii
